<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>aut</string>
	</array>
	<key>name</key>
	<string>Autonomy</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>variables</string>
			<key>match</key>
			<string>\$\w+\b</string>
			<key>name</key>
			<string>variable.other.autonomy</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>operator names</string>
			<key>match</key>
			<string>\.\w+\b</string>
			<key>name</key>
			<string>entity.name.function.autonomy</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keyword operators</string>
			<key>match</key>
			<string>(:=|=&gt;)</string>
			<key>name</key>
			<string>keyword.operator.autonomy</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>operators</string>
			<key>match</key>
			<string>[+\-*/=&lt;&gt;]+</string>
			<key>name</key>
			<string>entity.name.function.autonomy</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>numeric constants</string>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.autonomy</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keywords</string>
			<key>match</key>
			<string>\b\w+\b</string>
			<key>name</key>
			<string>keyword.other.autonomy</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>single line plain comment</string>
			<key>match</key>
			<string>#-.*$</string>
			<key>name</key>
			<string>comment.line.autonomy</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#{</string>
			<key>comment</key>
			<string>delimited plain comment</string>
			<key>end</key>
			<string>#}</string>
			<key>name</key>
			<string>comment.block.autonomy</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>single line documentation</string>
			<key>match</key>
			<string>#[#@].*$</string>
			<key>name</key>
			<string>comment.documentation.autonomy</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.autonomy</string>
	<key>uuid</key>
	<string>7f658267-1d5d-4821-869b-fbb836c06742</string>
</dict>
</plist>
